# Generated by Django 5.0.7 on 2024-08-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_department_order_orderitem_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='user',
        ),
    ]
