# Generated by Django 5.0.7 on 2024-08-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
