# Generated by Django 5.0.7 on 2024-08-14 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventorylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='categories',
            new_name='allowed_categories',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='quantity_ordered',
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='new_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='previous_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
