# Generated by Django 5.0.7 on 2024-08-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rename_categories_department_allowed_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='allowed_categories',
            new_name='accessible_categories',
        ),
    ]
